const arr = [
	{
		id: 1,
		name: 'Августин Иппонийский блж.',
		century: 5,
		active: 1,
		ekzeget_type: {
			id: 1,
			title: 'Святые Отцы и Учителя',
			active: 1,
		},
		investigated: false,
		interpretation: true,
	},
	{
		id: 4,
		name: 'Толковая Библия А.П. Лопухина',
		century: 20,
		active: 1,
		ekzeget_type: {
			id: 2,
			title: 'православные авторы',
			active: 1,
		},
		investigated: false,
		interpretation: true,
	},
	{
		id: 5,
		name: 'Феофилакт Болгарский блж.',
		century: 11,
		active: 1,
		ekzeget_type: {
			id: 1,
			title: 'Святые Отцы и Учителя',
			active: 1,
		},
		investigated: false,
		interpretation: true,
	},
	{
		id: 7,
		name: 'Ориген',
		century: 3,
		active: 1,
		ekzeget_type: {
			id: 3,
			title: 'неоднозначные авторы',
			active: 1,
		},
		investigated: false,
		interpretation: true,
	},
	{
		id: 8,
		name: 'Аверкий (Таушев) архиеп.',
		century: 20,
		active: 1,
		ekzeget_type: {
			id: 2,
			title: 'православные авторы',
			active: 1,
		},
		investigated: false,
		interpretation: true,
	},
	{
		id: 9,
		name: 'Ефрем Сирин прп.',
		century: 4,
		active: 1,
		ekzeget_type: {
			id: 1,
			title: 'Святые Отцы и Учителя',
			active: 1,
		},
		investigated: false,
		interpretation: true,
	},
	{
		id: 11,
		name: 'Анонимный комментарий',
		century: 4,
		active: 1,
		ekzeget_type: {
			id: 1,
			title: 'Святые Отцы и Учителя',
			active: 1,
		},
		investigated: false,
		interpretation: true,
	},
	{
		id: 16,
		name: 'Афанасий Великий свт.',
		century: 4,
		active: 1,
		ekzeget_type: {
			id: 1,
			title: 'Святые Отцы и Учителя',
			active: 1,
		},
		investigated: false,
		interpretation: true,
	},
	{
		id: 28,
		name: 'Евфимий Зигабен',
		century: 11,
		active: 1,
		ekzeget_type: {
			id: 1,
			title: 'Святые Отцы и Учителя',
			active: 1,
		},
		investigated: false,
		interpretation: true,
	},
	{
		id: 29,
		name: 'Амвросий Медиоланский свт.',
		century: 4,
		active: 1,
		ekzeget_type: {
			id: 1,
			title: 'Святые Отцы и Учителя',
			active: 1,
		},
		investigated: false,
		interpretation: true,
	},
	{
		id: 32,
		name: 'Игнатий (Брянчанинов) свт.',
		century: 19,
		active: 1,
		ekzeget_type: {
			id: 1,
			title: 'Святые Отцы и Учителя',
			active: 1,
		},
		investigated: false,
		interpretation: true,
	},
	{
		id: 33,
		name: 'Иероним Стридонский блж.',
		century: 4,
		active: 1,
		ekzeget_type: {
			id: 1,
			title: 'Святые Отцы и Учителя',
			active: 1,
		},
		investigated: false,
		interpretation: true,
	},
	{
		id: 35,
		name: 'Иларий Пиктавийский свт.',
		century: 4,
		active: 1,
		ekzeget_type: {
			id: 1,
			title: 'Святые Отцы и Учителя',
			active: 1,
		},
		investigated: false,
		interpretation: true,
	},
	{
		id: 36,
		name: 'Иоанн Златоуст свт.',
		century: 4,
		active: 1,
		ekzeget_type: {
			id: 1,
			title: 'Святые Отцы и Учителя',
			active: 1,
		},
		investigated: false,
		interpretation: true,
	},
	{
		id: 38,
		name: 'Иоанн Кронштадтский прав.',
		century: 20,
		active: 1,
		ekzeget_type: {
			id: 1,
			title: 'Святые Отцы и Учителя',
			active: 1,
		},
		investigated: false,
		interpretation: true,
	},
	{
		id: 40,
		name: 'Исидор Пелусиот прп.',
		century: 5,
		active: 1,
		ekzeget_type: {
			id: 1,
			title: 'Святые Отцы и Учителя',
			active: 1,
		},
		investigated: false,
		interpretation: true,
	},
	{
		id: 49,
		name: 'Максим Исповедник прп.',
		century: 7,
		active: 1,
		ekzeget_type: {
			id: 1,
			title: 'Святые Отцы и Учителя',
			active: 1,
		},
		investigated: false,
		interpretation: true,
	},
	{
		id: 50,
		name: 'Мефодий (Кульман) еп.',
		century: 20,
		active: 1,
		ekzeget_type: {
			id: 2,
			title: 'православные авторы',
			active: 1,
		},
		investigated: false,
		interpretation: true,
	},
	{
		id: 51,
		name: 'Михаил (Лузин) еп.',
		century: 19,
		active: 1,
		ekzeget_type: {
			id: 2,
			title: 'православные авторы',
			active: 1,
		},
		investigated: false,
		interpretation: true,
	},
	{
		id: 53,
		name: 'Никифор (Феотокис) архиеп.',
		century: 18,
		active: 1,
		ekzeget_type: {
			id: 2,
			title: 'православные авторы',
			active: 1,
		},
		investigated: false,
		interpretation: true,
	},
	{
		id: 56,
		name: 'Нил Синайский прп.',
		century: 5,
		active: 1,
		ekzeget_type: {
			id: 1,
			title: 'Святые Отцы и Учителя',
			active: 1,
		},
		investigated: false,
		interpretation: true,
	},
	{
		id: 67,
		name: 'Феодорит Кирский блж.',
		century: 5,
		active: 1,
		ekzeget_type: {
			id: 1,
			title: 'Святые Отцы и Учителя',
			active: 1,
		},
		investigated: false,
		interpretation: true,
	},
	{
		id: 70,
		name: 'Хроматий Аквилейский еп.',
		century: 5,
		active: 1,
		ekzeget_type: {
			id: 1,
			title: 'Святые Отцы и Учителя',
			active: 1,
		},
		investigated: false,
		interpretation: true,
	},
	{
		id: 75,
		name: 'Епифаний Кипрский свт.',
		century: 4,
		active: 1,
		ekzeget_type: {
			id: 1,
			title: 'Святые Отцы и Учителя',
			active: 1,
		},
		investigated: false,
		interpretation: true,
	},
	{
		id: 78,
		name: 'Иннокентий Херсонский свт.',
		century: 19,
		active: 1,
		ekzeget_type: {
			id: 1,
			title: 'Святые Отцы и Учителя',
			active: 1,
		},
		investigated: false,
		interpretation: true,
	},
	{
		id: 80,
		name: 'Филарет (Дроздов) свт.',
		century: 19,
		active: 1,
		ekzeget_type: {
			id: 1,
			title: 'Святые Отцы и Учителя',
			active: 1,
		},
		investigated: false,
		interpretation: true,
	},
	{
		id: 82,
		name: 'Фотий Константинопольский свт.',
		century: 9,
		active: 1,
		ekzeget_type: {
			id: 1,
			title: 'Святые Отцы и Учителя',
			active: 1,
		},
		investigated: false,
		interpretation: true,
	},
	{
		id: 86,
		name: 'Гладков Б.И.',
		century: 19,
		active: 1,
		ekzeget_type: {
			id: 2,
			title: 'православные авторы',
			active: 1,
		},
		investigated: false,
		interpretation: true,
	},
	{
		id: 88,
		name: 'Иоанн Дамаскин прп.',
		century: 8,
		active: 1,
		ekzeget_type: {
			id: 1,
			title: 'Святые Отцы и Учителя',
			active: 1,
		},
		investigated: false,
		interpretation: true,
	},
	{
		id: 90,
		name: 'Макарий (Булгаков) митр.',
		century: 19,
		active: 1,
		ekzeget_type: {
			id: 2,
			title: 'православные авторы',
			active: 1,
		},
		investigated: false,
		interpretation: true,
	},
	{
		id: 114,
		name: 'Иванов А.В. проф.',
		century: 19,
		active: 1,
		ekzeget_type: {
			id: 2,
			title: 'православные авторы',
			active: 1,
		},
		investigated: false,
		interpretation: true,
	},
	{
		id: 115,
		name: 'Троицкие листки игумена Пантелеимона',
		century: 19,
		active: 1,
		ekzeget_type: {
			id: 2,
			title: 'православные авторы',
			active: 1,
		},
		investigated: false,
		interpretation: true,
	},
	{
		id: 140,
		name: 'Иов (Гумеров) иером.',
		century: 21,
		active: 1,
		ekzeget_type: {
			id: 2,
			title: 'православные авторы',
			active: 1,
		},
		investigated: false,
		interpretation: true,
	},
	{
		id: 143,
		name: 'Ипполит Римский сщмч.',
		century: 2,
		active: 1,
		ekzeget_type: {
			id: 1,
			title: 'Святые Отцы и Учителя',
			active: 1,
		},
		investigated: false,
		interpretation: true,
	},
	{
		id: 146,
		name: 'Иустин Философ мч.',
		century: 2,
		active: 1,
		ekzeget_type: {
			id: 1,
			title: 'Святые Отцы и Учителя',
			active: 1,
		},
		investigated: false,
		interpretation: true,
	},
	{
		id: 168,
		name: 'Клеон Роджерс',
		century: 21,
		active: 1,
		ekzeget_type: {
			id: 5,
			title: 'инославные',
			active: 1,
		},
		investigated: true,
		interpretation: false,
	},
	{
		id: 176,
		name: 'Олег Стеняев прот.',
		century: 21,
		active: 1,
		ekzeget_type: {
			id: 2,
			title: 'православные авторы',
			active: 1,
		},
		investigated: false,
		interpretation: true,
	},
	{
		id: 192,
		name: 'Новая Женевская учебная Библия',
		century: 20,
		active: 1,
		ekzeget_type: {
			id: 5,
			title: 'инославные',
			active: 1,
		},
		investigated: false,
		interpretation: true,
	},
	{
		id: 203,
		name: 'Культурно-исторический комментарий',
		century: 21,
		active: 1,
		ekzeget_type: {
			id: 5,
			title: 'инославные',
			active: 1,
		},
		investigated: true,
		interpretation: false,
	},
	{
		id: 205,
		name: 'Юлий Африкан',
		century: 3,
		active: 1,
		ekzeget_type: {
			id: 1,
			title: 'Святые Отцы и Учителя',
			active: 1,
		},
		investigated: false,
		interpretation: true,
	},
	{
		id: 208,
		name: 'Александр Глаголев сщмч.',
		century: 20,
		active: 1,
		ekzeget_type: {
			id: 1,
			title: 'Святые Отцы и Учителя',
			active: 1,
		},
		investigated: false,
		interpretation: true,
	},
	{
		id: 212,
		name: 'Богословский М.И. проф.',
		century: 19,
		active: 1,
		ekzeget_type: {
			id: 2,
			title: 'православные авторы',
			active: 1,
		},
		investigated: false,
		interpretation: true,
	},
	{
		id: 222,
		name: 'Онуфрий (Гагалюк) сщмч.',
		century: 20,
		active: 1,
		ekzeget_type: {
			id: 1,
			title: 'Святые Отцы и Учителя',
			active: 1,
		},
		investigated: false,
		interpretation: true,
	},
	{
		id: 261,
		name: 'Севир Антиохийский патр.',
		century: 6,
		active: 1,
		ekzeget_type: {
			id: 4,
			title: 'еретики, осужденные Церковью',
			active: 1,
		},
		investigated: false,
		interpretation: true,
	},
	{
		id: 312,
		name: 'Алфавитная синтагма',
		century: 14,
		active: 1,
		ekzeget_type: {
			id: 1,
			title: 'Святые Отцы и Учителя',
			active: 1,
		},
		investigated: false,
		interpretation: true,
	},
	{
		id: 346,
		name: 'Муретов М.Д. проф.',
		century: 20,
		active: 1,
		ekzeget_type: {
			id: 2,
			title: 'православные авторы',
			active: 1,
		},
		investigated: false,
		interpretation: true,
	},
	{
		id: 354,
		name: 'Иоанн Бухарев прот.',
		century: 20,
		active: 1,
		ekzeget_type: {
			id: 2,
			title: 'православные авторы',
			active: 1,
		},
		investigated: false,
		interpretation: true,
	},
];
